import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full bg-red-400 flex justify-center items-center">
        {children}
      </body>
    </html>
  );
}
